name: .NET

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/
    - name: Publish 
      run: dotnet publish src/ --configuration Release
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: src/bin/Release/net8.0/publish/wwwroot # default is _site/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
